In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/online_retail.csv")

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
df.shape

(541909, 8)

In [6]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [8]:
df.duplicated().sum()

np.int64(5268)

In [9]:
df[df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

In [10]:
df1 = df.drop_duplicates(inplace = True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.shape

(536641, 8)

In [13]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
dtype: int64

In [14]:
df.head(8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom

In [15]:
df2 = df.dropna().copy()

In [16]:
df2.shape

(401604, 8)

In [17]:
df2.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [18]:
df2.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [19]:
df2["InvoiceNo"].astype(str).str.startswith('C').sum()

np.int64(8872)

In [20]:
df2[df2["InvoiceNo"].astype(str).str.startswith('C')].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [21]:
df[df["StockCode"].astype(str).str.endswith('a')].head(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
5443,536862,84872a,TEATIME FUNKY FLOWER BACKPACK FOR 2,2,2010-12-03 11:13:00,11.02,NaN,United Kingdom
5448,536862,85039a,SET/4 RED MINI ROSE CANDLE IN BOWL,1,2010-12-03 11:13:00,3.36,NaN,United Kingdom
5672,536865,84559a,3D SHEET OF DOG STICKERS,1,2010-12-03 11:28:00,1.69,NaN,United Kingdom
5675,536865,84884a,ANT WHITE WIRE HEART SPIRAL,1,2010-12-03 11:28:00,8.47,NaN,United Kingdom
5677,536865,85014a,BLACK/BLUE POLKADOT UMBRELLA,2,2010-12-03 11:28:00,12.72,NaN,United Kingdom
5680,536865,85039a,SET/4 RED MINI ROSE CANDLE IN BOWL,1,2010-12-03 11:28:00,3.36,NaN,United Kingdom
6960,536982,85049a,TRADITIONAL CHRISTMAS RIBBONS,10,2010-12-03 14:27:00,3.36,NaN,United Kingdom
6964,536982,85123a,WHITE HANGING HEART T-LIGHT HOLDER,35,2010-12-03 14:27:00,6.77,NaN,United Kingdom
15773,537640,84989a,75 GREEN FAIRY CAKE CASES,1,2010-12-07 15:31:00,2.13,NaN,United Kingdom
15777,537640,85049a,TRADITIONAL CHRISTMAS RIBBONS,55,2010-12-07 15:31:00,3.36,NaN,United Kingdom
15781,537640,85123a,WHITE HANGING HEART T-LIGHT HOLDER,46,2010-12-07 15:31:00,6.77,NaN,United Kingdom
15875,537641,84872a,TEATIME FUNKY FLOWER BACKPACK FOR 2,1,2010-12-07 15:32:00,11.02,NaN,United Kingdom
15971,537642,84559a,3D SHEET OF DOG STICKERS,1,2010-12-07 15:33:00,1.69,NaN,United Kingdom
15976,537642,84884a,ANT WHITE WIRE HEART SPIRAL,4,2010-12-07 15:33:00,8.47,NaN,United Kingdom
16086,537643,72351a,SET/6 TURQUOISE BUTTERFLY T-LIGHTS,2,2010-12-07 15:34:00,4.21,NaN,United Kingdom

In [22]:
df2['StockCode'].value_counts()

StockCode
85123A    2065
22423     1894
85099B    1659
47566     1409
84879     1405
          ...
90181A       1
90199B       1
90102        1
84550        1
90214O       1
Name: count, Length: 3684, dtype: int64

In [23]:
df2["Description"].value_counts()

Description
WHITE HANGING HEART T-LIGHT HOLDER     2058
REGENCY CAKESTAND 3 TIER               1894
JUMBO BAG RED RETROSPOT                1659
PARTY BUNTING                          1409
ASSORTED COLOUR BIRD ORNAMENT          1405
                                       ...
LETTER "W" BLING KEY RING                 1
CROCHET LILAC/RED BEAR KEYRING            1
MIDNIGHT BLUE CRYSTAL DROP EARRINGS       1
BLACK VINT ART DEC CRYSTAL BRACELET       1
WHITE STONE/CRYSTAL EARRINGS              1
Name: count, Length: 3896, dtype: int64

In [24]:
df2.sort_values(by="Quantity", ascending=False).head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.00,13256.0,United Kingdom
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,2011-10-27 12:26:00,0.21,12901.0,United Kingdom
206121,554868,22197,SMALL POPCORN HOLDER,4300,2011-05-27 10:52:00,0.72,13135.0,United Kingdom
97432,544612,22053,EMPIRE DESIGN ROSETTE,3906,2011-02-22 10:43:00,0.82,18087.0,United Kingdom
270885,560599,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,3186,2011-07-19 17:04:00,0.06,14609.0,United Kingdom
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2011-01-11 12:55:00,2.10,15749.0,United Kingdom
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2011-04-18 13:20:00,2.10,15749.0,United Kingdom
433788,573995,16014,SMALL CHINESE STYLE SCISSOR,3000,2011-11-02 11:24:00,0.32,16308.0,United Kingdom

In [25]:
df2[df2['Quantity'] == 80995]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom

In [26]:
df2[df2['Quantity' ] == 0]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [27]:
df2[df2['Quantity' ] <= 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [28]:
df2[df2['UnitPrice' ] <= 0.00]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647.0,Germany
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,2010-12-16 14:36:00,0.0,16560.0,United Kingdom
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,2010-12-21 13:45:00,0.0,14911.0,EIRE
47068,540372,22090,PAPER BUNTING RETROSPOT,24,2011-01-06 16:41:00,0.0,13081.0,United Kingdom
47070,540372,22553,PLASTERS IN TIN SKULLS,24,2011-01-06 16:41:00,0.0,13081.0,United Kingdom
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,2011-01-13 15:10:00,0.0,15107.0,United Kingdom
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,2011-02-10 13:08:00,0.0,17560.0,United Kingdom
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,2011-03-23 10:25:00,0.0,13239.0,United Kingdom
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,2011-03-30 12:45:00,0.0,13113.0,United Kingdom
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,2011-04-04 14:42:00,0.0,14410.0,United Kingdom
157042,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,2011-04-14 18:57:00,0.0,12457.0,Switzerland
187613,553000,47566,PARTY BUNTING,4,2011-05-12 15:21:00,0.0,17667.0,United Kingdom
198383,554037,22619,SET OF 6 SOLDIER SKITTLES,80,2011-05-20 14:13:00,0.0,12415.0,Australia
279324,561284,22167,OVAL WALL MIRROR DIAMANTE,1,2011-07-26 12:24:00,0.0,16818.0,United Kingdom
282912,561669,22960,JAM MAKING SET WITH JARS,11,2011-07-28 17:09:00,0.0,12507.0,Spain
285657,561916,M,Manual,1,2011-08-01 11:44:00,0.0,15581.0,United Kingdom
298054,562973,23157,SET OF 6 NATIVITY MAGNETS,240,2011-08-11 11:42:00,0.0,14911.0,EIRE
314745,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,2011-08-26 14:19:00,0.0,14646.0,Netherlands
314746,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,2011-08-26 14:19:00,0.0,14646.0,Netherlands
314747,564651,22955,36 FOIL STAR CAKE CASES,144,2011-08-26 14:19:00,0.0,14646.0,Netherlands
314748,564651,21786,POLKADOT RAIN HAT,144,2011-08-26 14:19:00,0.0,14646.0,Netherlands
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-09-25 12:22:00,0.0,16133.0,United Kingdom
361825,568384,M,Manual,1,2011-09-27 09:46:00,0.0,12748.0,United Kingdom
379913,569716,22778,GLASS CLOCHE SMALL,2,2011-10-06 08:17:00,0.0,15804.0,United Kingdom
395529,571035,M,Manual,1,2011-10-13 12:50:00,0.0,12446.0,RSA
420404,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,2011-10-26 14:36:00,0.0,18059.0,United Kingdom
436428,574138,23234,BISCUIT TIN VINTAGE CHRISTMAS,216,2011-11-03 11:26:00,0.0,12415.0,Australia
436597,574175,22065,CHRISTMAS PUDDING TRINKET POT,12,2011-11-03 11:47:00,0.0,14110.0,United Kingdom
436961,574252,M,Manual,1,2011-11-03 13:24:00,0.0,12437.0,France
439361,574469,22385,JUMBO BAG SPACEBOY DESIGN,12,2011-11-04 11:55:00,0.0,12431.0,Australia
446125,574879,22625,RED KITCHEN SCALES,2,2011-11-07 13:22:00,0.0,13014.0,United Kingdom
446793,574920,22899,CHILDREN'S APRON DOLLY GIRL,1,2011-11-07 16:34:00,0.0,13985.0,United Kingdom
446794,574920,23480,MINI LIGHTS WOODLAND MUSHROOMS,1,2011-11-07 16:34:00,0.0,13985.0,United Kingdom
454463,575579,22437,SET OF 9 BLACK SKULL BALLOONS,20,2011-11-10 11:49:00,0.0,13081.0,United Kingdom
454464,575579,22089,PAPER BUNTING VINTAGE PAISLEY,24,2011-11-10 11:49:00,0.0,13081.0,United Kingdom
479079,577129,22464,HANGING METAL HEART LANTERN,4,2011-11-17 19:52:00,0.0,15602.0,United Kingdom
479546,577168,M,Manual,1,2011-11-18 10:42:00,0.0,12603.0,Germany
480649,577314,23407,SET OF 2 TRAYS HOME SWEET HOME,2,2011-11-18 13:23:00,0.0,12444.0,Norway
485985,577696,M,Manual,1,2011-11-21 11:57:00,0.0,16406.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.0,13256.0,United Kingdom

In [29]:
df2['CustomerID'].value_counts()

CustomerID
17841.0    7812
14911.0    5898
14096.0    5128
12748.0    4459
14606.0    2759
           ...
17715.0       1
14705.0       1
13120.0       1
13829.0       1
17986.0       1
Name: count, Length: 4372, dtype: int64

In [30]:
df2.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [31]:
df2[df['CustomerID'] == 0]

C:\Users\Mahendiran\AppData\Local\Temp\ipykernel_53592\3028995142.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2[df['CustomerID'] == 0]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [32]:
df2['Country'].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Greece', 'Singapore', 'Lebanon',
       'United Arab Emirates', 'Saudi Arabia', 'Czech Republic', 'Canada',
       'Unspecified', 'Brazil', 'USA', 'European Community', 'Bahrain',
       'Malta', 'RSA'], dtype=object)

In [33]:
df2['InvoiceDate'] = pd.to_datetime(df2['InvoiceDate'])

In [34]:
df2['InvoiceDate'].dtype

dtype('<M8[ns]')

In [35]:
df2.shape

(401604, 8)

In [36]:
df2['Date'] = df2['InvoiceDate'].dt.date

In [37]:
df2['Time'] = df2['InvoiceDate'].dt.time

In [38]:
df2.drop(columns = ['InvoiceDate'],inplace = True)

In [39]:
df2 = df2[df2['Quantity'] >0.0].copy()

In [40]:
df2.shape

(392732, 9)

In [41]:
df3 = df2[(df2['StockCode'] != "M") & (df2['StockCode'] != "D")  ].copy()

In [42]:
df3.shape

(392447, 9)

In [43]:
df4 = df3[~(df3['UnitPrice'] <= 0.00)].copy()

In [44]:
df4.head(10)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date,Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,2010-12-01,08:26:00
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,2010-12-01,08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,7.65,17850.0,United Kingdom,2010-12-01,08:26:00
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,4.25,17850.0,United Kingdom,2010-12-01,08:26:00
7,536366,22633,HAND WARMER UNION JACK,6,1.85,17850.0,United Kingdom,2010-12-01,08:28:00
8,536366,22632,HAND WARMER RED POLKA DOT,6,1.85,17850.0,United Kingdom,2010-12-01,08:28:00
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,1.69,13047.0,United Kingdom,2010-12-01,08:34:00

In [45]:
df4["StockCode"].value_counts()

StockCode
85123A    2023
22423     1713
85099B    1615
84879     1395
47566     1389
          ...
84206B       1
90212B       1
35597B       1
84613C       1
84802A       1
Name: count, Length: 3664, dtype: int64

In [46]:
no_alpha_end = df4[df4['StockCode'].str.match(r'^\d+$')]

len(no_alpha_end)

358277

In [47]:
alpha_end = df4[df4['StockCode'].str[-1].str.isalpha()]

alpha_end.shape

(34003, 9)

In [48]:
df4.head(10)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date,Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,2010-12-01,08:26:00
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,2010-12-01,08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,7.65,17850.0,United Kingdom,2010-12-01,08:26:00
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,4.25,17850.0,United Kingdom,2010-12-01,08:26:00
7,536366,22633,HAND WARMER UNION JACK,6,1.85,17850.0,United Kingdom,2010-12-01,08:28:00
8,536366,22632,HAND WARMER RED POLKA DOT,6,1.85,17850.0,United Kingdom,2010-12-01,08:28:00
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,1.69,13047.0,United Kingdom,2010-12-01,08:34:00

In [49]:
alpha_end2 = df4[df4['InvoiceNo'].str.isalpha()]

alpha_end2.shape

(0, 9)

In [50]:
print("Negative Quantity:", (df4['Quantity'] < 0).sum())
print("Zero or Negative Price:", (df4['UnitPrice'] <= 0).sum())

Negative Quantity: 0
Zero or Negative Price: 0

In [51]:
print("Unique Customers:", df4['CustomerID'].nunique())
print("Unique StockCodes:", df4['StockCode'].nunique())
print("Unique Invoices:", df4['InvoiceNo'].nunique())

Unique Customers: 4335
Unique StockCodes: 3664
Unique Invoices: 18468

In [52]:
print("Min Date:", df4['Date'].min())
print("Max Date:", df4['Date'].max())

Min Date: 2010-12-01
Max Date: 2011-12-09

In [ ]:
df5 = df4[df4['StockCode'] != 'BANK CHARGES'].copy()

In [ ]:
df5[df5['StockCode'] == 'Post']

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, UnitPrice, CustomerID, Country, Date, Time]
Index: []

In [ ]:
df5.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date,Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,2010-12-01,08:26:00
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,2010-12-01,08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00

In [ ]:
df5['Spending $'] = df['Quantity']*df['UnitPrice']

In [ ]:
df5.drop(columns = ['Description'], inplace = True)

In [ ]:
df5.head()

,InvoiceNo,StockCode,Quantity,UnitPrice,CustomerID,Country,Date,Time,Spending $
0,536365,85123A,6,2.55,17850.0,United Kingdom,2010-12-01,08:26:00,15.30
1,536365,71053,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00,20.34
2,536365,84406B,8,2.75,17850.0,United Kingdom,2010-12-01,08:26:00,22.00
3,536365,84029G,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00,20.34
4,536365,84029E,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00,20.34

In [ ]:
last_purchase = df5.groupby('CustomerID')['Date'].max().reset_index()

In [ ]:
snapshot_date = df5['Date'].max() + pd.Timedelta(days=1)

In [ ]:
last_purchase['Date'] = pd.to_datetime(last_purchase['Date'])

In [ ]:
df5['Date'] = pd.to_datetime(df5['Date'])

In [ ]:
snapshot_date = df5['Date'].max() + pd.Timedelta(days=1)
df5['Recency'] = (snapshot_date - last_purchase['Date']).dt.days

In [ ]:
df5.head()

NameError: name 'df5' is not defined

In [ ]:
import pandas as pd

# -----------------------------
# 1. Ensure Date is datetime
# -----------------------------
df['Date'] = pd.to_datetime(df['Date'])

# -----------------------------
# 2. Create Snapshot Date
# -----------------------------
snapshot_date = df['Date'].max() + pd.Timedelta(days=1)

# -----------------------------
# 3. Create RFM Features per Customer
# -----------------------------
rfm = df.groupby('CustomerID').agg({
    'Date': 'max',                 # Last purchase date
    'InvoiceNo': 'nunique',        # Number of orders
    'Spending $': 'sum'            # Total spending
}).reset_index()

# -----------------------------
# 4. Calculate Recency
# -----------------------------
rfm['Recency'] = (snapshot_date - rfm['Date']).dt.days

# -----------------------------
# 5. Rename Columns
# -----------------------------
rfm.rename(columns={
    'InvoiceNo': 'Frequency',
    'Spending $': 'Monetary'
}, inplace=True)

# Keep only useful columns for merge
rfm = rfm[['CustomerID', 'Recency', 'Frequency', 'Monetary']]

# -----------------------------
# 6. Merge Back to Original Data
# -----------------------------
df = df.merge(rfm, on='CustomerID', how='left')

# -----------------------------
# 7. Check Result
# -----------------------------
print(df.head())

In [57]:
df4.sample(5)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date,Time
410533,572106,20971,PINK BLUE FELT CRAFT TRINKET BOX,12,1.25,15058.0,United Kingdom,2011-10-20,17:04:00
117310,546378,21523,DOORMAT FANCY FONT HOME SWEET HOME,2,7.95,14329.0,United Kingdom,2011-03-11,12:17:00
166123,550899,22956,36 FOIL HEART CAKE CASES,6,2.10,13505.0,Switzerland,2011-04-21,12:07:00
173060,551650,21775,DECORATIVE FLORE BATHROOM BOTTLE,12,1.25,13089.0,United Kingdom,2011-05-03,12:02:00
107270,545423,22682,FRENCH BLUE METAL DOOR SIGN 7,10,1.25,15643.0,United Kingdom,2011-03-02,14:34:00

In [ ]:
df4[df4['CustomerID'] == 17850.0]['Date'].value_counts()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date,Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,2010-12-01,08:26:00
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,2010-12-01,08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00
...,...,...,...,...,...,...,...,...,...
4540,536790,22752,SET 7 BABUSHKA NESTING BOXES,4,7.65,17850.0,United Kingdom,2010-12-02,15:26:00
4541,536790,22803,IVORY EMBROIDERED QUILT,3,35.75,17850.0,United Kingdom,2010-12-02,15:26:00
4542,536790,21730,GLASS STAR FROSTED T-LIGHT HOLDER,12,4.25,17850.0,United Kingdom,2010-12-02,15:26:00
4543,536791,22632,HAND WARMER RED POLKA DOT,12,1.85,17850.0,United Kingdom,2010-12-02,15:27:00
4544,536791,22633,HAND WARMER UNION JACK,12,1.85,17850.0,United Kingdom,2010-12-02,15:27:00

In [58]:
df4[df4['CustomerID'] == 13505.0]['Date'].value_counts()

Date
2011-09-28    92
2011-04-21    54
2011-05-31    42
2011-06-26    27
Name: count, dtype: int64

In [59]:
df4["TotalPrice"] = df4["Quantity"] * df4["UnitPrice"]

In [ ]:
snapshot_date = df4["Date"].max() + pd.Timedelta(days=1)
rfm = df4.groupby("CustomerID").agg({
    "Date": lambda x: (snapshot_date - x.max()).days,  # Recency
    "InvoiceNo": "count",                                     # Frequency
    "TotalPrice": "sum"                                       # Monetary
})

rfm.columns = ["Recency", "Frequency", "Monetary"]
rfm = rfm.reset_index()

In [64]:
type(rfm)

pandas.core.frame.DataFrame

In [65]:
rfm.head()

   CustomerID  Recency  Frequency  Monetary
0     12346.0      326          1  77183.60
1     12347.0        3        182   4310.00
2     12348.0       76         31   1797.24
3     12349.0       19         73   1757.55
4     12350.0      311         17    334.40

In [66]:
df4.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Date,Time,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,2010-12-01,08:26:00,15.30
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,2010-12-01,08:26:00,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,2010-12-01,08:26:00,20.34

In [67]:
rfm.shape

(4335, 4)